### ISSUE TITLE
Cooperate with early-retirement

### ISSUE THREAD

**Issue by jonestristand** [axkirillov/hbac.nvim#23]
Trying to get this to work well with early-retirement.nvim... Is there a way to hook pinning a buffer so that I can set `vim.b.ignore_early_retirement = true` on the buffer as well and make early-retirement.nvim also ignore pinned buffers?

**Comment by axkirillov** [comment]
Currently we do not let users define callbacks for the pin function, but that's an interesting idea. I would be open to look at a PR for this. The way I would do this is let the user define a function that runs every time toggle_pin is run. Feel free to ask any further questions.

**Comment by ADIX7** [comment]
I have the same issue. What about an Autocmd with the bufnr and pinned/unpinned as arguments?

**Comment by axkirillov** [comment]
Hi! I'm not sure what event to you want to create an autocmd for. But I am open to any interesting PRs.

**Comment by ADIX7** [comment]
Here is a PR for this: https://github.com/axkirillov/hbac.nvim/pull/29

To use it:
```lua
vim.api.nvim_create_autocmd("User", {
    callback = function(opts)
        local bufnr = opts.data.bufnr
        local state = opts.data.state
        vim.api.nvim_buf_set_var(bufnr, "ignore_early_retirement", state == "pinned")
    end,
    pattern = "HBACPinned",
})
```

**Comment by axkirillov** [comment]
Solved with https://github.com/axkirillov/hbac.nvim/pull/29
