### ISSUE TITLE
Autopin

### ISSUE THREAD

**Issue by serhez** [axkirillov/hbac.nvim#30]
Hello! I noticed that my buffers are being pinned very often without me doing so. Hence, I went into your code and tried to find any mechanism triggering this. I found the `autopin` set of autocmds; this seems to be what's causing this behavior. I tried looking in the readme but could not find any info about it. Could you shed some light on this (i.e., why is that there, is there any way to turn it off, etc.)? Thanks!

**Comment by al-ce** [comment]
When you enter Insert mode or the buffer is modified, hbac automatically pins the buffer. The [description](https://github.com/axkirillov/hbac.nvim?tab=readme-ov-file#description) in the readme explains it well. The assumption is that if you go into insert mode/edit a buffer, it is of interest to you, and it shouldn't be autoclosed even if the buffer threshold is passed.

A way to disable it could be to add this to your config:

```lua
  require("hbac").setup(opts)  -- whatever your opts are

  -- make sure this is after the setup call
  local autoclose_group = require("hbac.autocommands").autopin.name
  vim.api.nvim_del_augroup_by_name(autoclose_group)
```

**Comment by axkirillov** [comment]
Thank you @al-ce
